2015/05/10 11:12:53 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`organaiser`.`tbl_records`, CONSTRAINT `FK_records_users` FOREIGN KEY (`user_id`) REFERENCES `tbl_users` (`id`) ON DELETE CASCADE). The SQL statement executed was: INSERT INTO `tbl_records` (`title`, `content`, `start_date`, `finish_date`, `user_id`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4).
in E:\XAMPP\htdocs\organaiser\www\protected\controllers\RecordsController.php (73)
in E:\XAMPP\htdocs\organaiser\www\index.php (13)
2015/05/10 11:12:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`organaiser`.`tbl_records`, CONSTRAINT `FK_records_users` FOREIGN KEY (`user_id`) REFERENCES `tbl_users` (`id`) ON DELETE CASCADE). The SQL statement executed was: INSERT INTO `tbl_records` (`title`, `content`, `start_date`, `finish_date`, `user_id`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4)' in E:\XAMPP\htdocs\organaiser\framework\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 E:\XAMPP\htdocs\organaiser\framework\yii\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 E:\XAMPP\htdocs\organaiser\framework\yii\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 E:\XAMPP\htdocs\organaiser\www\protected\controllers\RecordsController.php(73): CActiveRecord->save()
#3 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\actions\CInlineAction.php(49): RecordsController->actionCreate()
#4 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php(291): CFilterChain->run()
#11 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php(282): CController->run('create')
#13 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('records/create')
#14 E:\XAMPP\htdocs\organaiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 E:\XAMPP\htdocs\organaiser\www\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/www/index.php?r=records/create
HTTP_REFERER=http://organaiser.local/www/index.php?r=records/create
---
2015/05/13 17:19:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "post".' in E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post')
#1 E:\XAMPP\htdocs\organaiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\XAMPP\htdocs\organaiser\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/www/index.php?r=post
---
2015/05/13 17:20:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "view".' in E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('view')
#1 E:\XAMPP\htdocs\organaiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\XAMPP\htdocs\organaiser\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/www/index.php?r=view
---
2015/05/14 15:34:11 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "GuestIndex".' in E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php:878
Stack trace:
#0 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php(782): CController->renderPartial('GuestIndex', NULL, true)
#1 E:\XAMPP\htdocs\organaiser\www\protected\controllers\SiteController.php(34): CController->render('GuestIndex')
#2 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#8 E:\XAMPP\htdocs\organaiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 E:\XAMPP\htdocs\organaiser\www\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/www/
---
2015/05/15 10:54:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "records".' in E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php:483
Stack trace:
#0 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php(270): CController->missingAction('records')
#1 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php(282): CController->run('records')
#2 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/records')
#3 E:\XAMPP\htdocs\organaiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 E:\XAMPP\htdocs\organaiser\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/www/index.php?r=site/records
---
2015/05/19 15:37:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "images".' in E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php:483
Stack trace:
#0 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/log...')
#3 E:\XAMPP\htdocs\organaiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 E:\XAMPP\htdocs\organaiser\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/www/site/images/logo_1024.jpg
HTTP_REFERER=http://organaiser.local/www/site/
---
2015/05/19 15:38:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "images".' in E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php:483
Stack trace:
#0 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CController.php(270): CController->missingAction('images')
#1 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php(282): CController->run('images')
#2 E:\XAMPP\htdocs\organaiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/images/log...')
#3 E:\XAMPP\htdocs\organaiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 E:\XAMPP\htdocs\organaiser\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/www/site/images/logo_1024.jpg
HTTP_REFERER=http://organaiser.local/www/site/
---
2015/05/19 16:16:50 [error] [exception.CException] exception 'CException' with message 'Property "User.login" is not defined.' in E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CComponent.php:130
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('login')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\helpers\CHtml.php(2728): CActiveRecord->__get('login')
#2 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\helpers\CHtml.php(2451): CHtml::resolveValue(Object(User), 'login')
#3 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\helpers\CHtml.php(1533): CHtml::activeInputField('text', Object(User), 'login', Array)
#4 E:\XAMPP\htdocs\organiser\www\protected\views\user\registration.php(10): CHtml::activeTextField(Object(User), 'login')
#5 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CBaseController.php(126): require('E:\\XAMPP\\htdocs...')
#6 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\XAMPP\\htdocs...', Array, true)
#7 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(869): CBaseController->renderFile('E:\\XAMPP\\htdocs...', Array, true)
#8 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(782): CController->renderPartial('registration', Array, true)
#9 E:\XAMPP\htdocs\organiser\www\protected\controllers\UserController.php(80): CController->render('registration', Array)
#10 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\actions\CInlineAction.php(49): UserController->actionRegistration()
#11 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(282): CController->run('registration')
#15 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/registrati...')
#16 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/user/registration
---
2015/05/19 16:18:19 [error] [exception.CException] exception 'CException' with message 'Property "User.login" is not defined.' in E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CComponent.php:130
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('login')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\helpers\CHtml.php(2728): CActiveRecord->__get('login')
#2 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\helpers\CHtml.php(2451): CHtml::resolveValue(Object(User), 'login')
#3 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\helpers\CHtml.php(1533): CHtml::activeInputField('text', Object(User), 'login', Array)
#4 E:\XAMPP\htdocs\organiser\www\protected\views\user\registration.php(10): CHtml::activeTextField(Object(User), 'login')
#5 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CBaseController.php(126): require('E:\\XAMPP\\htdocs...')
#6 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\XAMPP\\htdocs...', Array, true)
#7 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(869): CBaseController->renderFile('E:\\XAMPP\\htdocs...', Array, true)
#8 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(782): CController->renderPartial('registration', Array, true)
#9 E:\XAMPP\htdocs\organiser\www\protected\controllers\UserController.php(80): CController->render('registration', Array)
#10 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\actions\CInlineAction.php(49): UserController->actionRegistration()
#11 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(282): CController->run('registration')
#15 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/registrati...')
#16 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/user/registration
---
2015/05/19 16:31:49 [error] [exception.CException] exception 'CException' with message 'Property "User.login" is not defined.' in E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CComponent.php:130
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('login')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\helpers\CHtml.php(2728): CActiveRecord->__get('login')
#2 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\helpers\CHtml.php(2451): CHtml::resolveValue(Object(User), 'login')
#3 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\helpers\CHtml.php(1533): CHtml::activeInputField('text', Object(User), 'login', Array)
#4 E:\XAMPP\htdocs\organiser\www\protected\views\user\registration.php(10): CHtml::activeTextField(Object(User), 'login')
#5 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CBaseController.php(126): require('E:\\XAMPP\\htdocs...')
#6 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\XAMPP\\htdocs...', Array, true)
#7 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(869): CBaseController->renderFile('E:\\XAMPP\\htdocs...', Array, true)
#8 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(782): CController->renderPartial('registration', Array, true)
#9 E:\XAMPP\htdocs\organiser\www\protected\controllers\UserController.php(80): CController->render('registration', Array)
#10 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\actions\CInlineAction.php(49): UserController->actionRegistration()
#11 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(282): CController->run('registration')
#15 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/registrati...')
#16 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/user/registration
---
2015/05/19 16:34:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index
---
2015/05/19 16:34:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "guestindex".' in E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('guestindex')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/guestindex
---
2015/05/19 16:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "guestindex".' in E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php:483
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(270): CController->missingAction('guestindex')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(282): CController->run('guestindex')
#2 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/guestindex')
#3 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/site/guestindex
---
2015/05/21 15:06:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://organiser.local/
---
2015/05/21 15:08:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/logo_1024.jpg".' in E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('images/logo_102...')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/images/logo_1024.jpg
HTTP_REFERER=http://organiser.local/index.php/site/index
---
2015/05/21 15:09:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/logo_1024.jpg".' in E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('images/logo_102...')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/images/logo_1024.jpg
HTTP_REFERER=http://organiser.local/index.php/site/index
---
2015/05/21 15:10:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/logo_1024.jpg".' in E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('images/logo_102...')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/images/logo_1024.jpg
HTTP_REFERER=http://organiser.local/index.php/site/index
---
2015/05/25 16:18:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://organiser.local/
---
2015/05/25 16:19:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/logo_1024.jpg".' in E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('images/logo_102...')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/images/logo_1024.jpg
HTTP_REFERER=http://organiser.local/index.php/site/index
---
2015/05/25 16:19:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "images/logo_1024.jpg".' in E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('images/logo_102...')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/images/logo_1024.jpg
HTTP_REFERER=http://organiser.local/index.php/site/index
---
2015/05/25 16:40:13 [error] [exception.CException] exception 'CException' with message 'Property "User.login" is not defined.' in E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CComponent.php:130
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('login')
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\helpers\CHtml.php(2728): CActiveRecord->__get('login')
#2 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\helpers\CHtml.php(2451): CHtml::resolveValue(Object(User), 'login')
#3 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\helpers\CHtml.php(1533): CHtml::activeInputField('text', Object(User), 'login', Array)
#4 E:\XAMPP\htdocs\organiser\www\protected\views\user\registration.php(10): CHtml::activeTextField(Object(User), 'login')
#5 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CBaseController.php(126): require('E:\\XAMPP\\htdocs...')
#6 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\XAMPP\\htdocs...', Array, true)
#7 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(869): CBaseController->renderFile('E:\\XAMPP\\htdocs...', Array, true)
#8 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(782): CController->renderPartial('registration', Array, true)
#9 E:\XAMPP\htdocs\organiser\www\protected\controllers\UserController.php(80): CController->render('registration', Array)
#10 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\actions\CInlineAction.php(49): UserController->actionRegistration()
#11 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(282): CController->run('registration')
#15 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/registrati...')
#16 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/user/registration
---
2015/05/25 16:47:33 [warning] [application] Failed to set unsafe attribute "verifyCode" of "User".
in E:\XAMPP\htdocs\organiser\www\protected\controllers\UserController.php (49)
in E:\XAMPP\htdocs\organiser\www\index.php (13)
2015/05/25 16:54:35 [warning] [application] Failed to set unsafe attribute "verifyCode" of "User".
in E:\XAMPP\htdocs\organiser\www\protected\controllers\UserController.php (49)
in E:\XAMPP\htdocs\organiser\www\index.php (13)
2015/05/25 16:55:06 [warning] [application] Failed to set unsafe attribute "verifyCode" of "User".
in E:\XAMPP\htdocs\organiser\www\protected\controllers\UserController.php (49)
in E:\XAMPP\htdocs\organiser\www\index.php (13)
2015/05/25 16:55:06 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`organiser`.`tbl_user`, CONSTRAINT `FK_user_organisation` FOREIGN KEY (`organisation_id`) REFERENCES `tbl_organisation` (`id`) ON DELETE CASCADE). The SQL statement executed was: INSERT INTO `tbl_user` (`username`, `password`, `email`, `first_name`, `last_name`, `profile`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5).
in E:\XAMPP\htdocs\organiser\www\protected\controllers\UserController.php (64)
in E:\XAMPP\htdocs\organiser\www\index.php (13)
2015/05/25 16:55:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`organiser`.`tbl_user`, CONSTRAINT `FK_user_organisation` FOREIGN KEY (`organisation_id`) REFERENCES `tbl_organisation` (`id`) ON DELETE CASCADE). The SQL statement executed was: INSERT INTO `tbl_user` (`username`, `password`, `email`, `first_name`, `last_name`, `profile`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)' in E:\XAMPP\htdocs\organiser\framework\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 E:\XAMPP\htdocs\organiser\framework\yii\framework\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 E:\XAMPP\htdocs\organiser\framework\yii\framework\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 E:\XAMPP\htdocs\organiser\www\protected\controllers\UserController.php(64): CActiveRecord->save()
#3 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\actions\CInlineAction.php(49): UserController->actionRegistration()
#4 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(282): CController->run('registration')
#8 E:\XAMPP\htdocs\organiser\framework\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/registrati...')
#9 E:\XAMPP\htdocs\organiser\framework\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 E:\XAMPP\htdocs\organiser\www\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/user/registration
HTTP_REFERER=http://organiser.local/user/registration
---
2015/05/25 17:31:20 [warning] [application] Failed to set unsafe attribute "organisation_name" of "User".
in E:\XAMPP\htdocs\organiser\www\protected\controllers\UserController.php (49)
in E:\XAMPP\htdocs\organiser\www\index.php (13)
2015/05/25 17:31:20 [warning] [application] Failed to set unsafe attribute "verifyCode" of "User".
in E:\XAMPP\htdocs\organiser\www\protected\controllers\UserController.php (49)
in E:\XAMPP\htdocs\organiser\www\index.php (13)
